# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: dex

before:
  hooks:
    - go mod tidy

builds:
  - id: dex
    main: ./cmd/tui
    binary: dex
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

nfpms:
  - id: dexchat-deb
    package_name: dexchat
    ids:
      - dex
    formats:
      - deb
      - rpm
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: dexchat
    homepage: https://dexchat.org
    maintainer: Leonardo Essia <leonardo@essia.dev>
    description: A modern and fast terminal IRC client
    license: MIT
    bindir: /usr/bin
    section: net
    priority: optional
    conflicts:
      - dex

checksum:
  name_template: checksums.txt

homebrew_casks:
  - name: dex
    repository:
      owner: dexchat
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/dexchat/dex
    description: IRC/TUI client for dexchat
    binaries:
      - dex
    caveats: |
      If macOS blocks dexchat, enable it by running the following command:
      
        xattr -d com.apple.quarantine "$(command -v dex)"

    commit_msg_template: "chore: update dex to {{ .Tag }}"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  abbrev: 7
  format: "[`{{ .SHA }}`](https://github.com/dexchat/dex/commit/{{ .SHA }}): {{ .Message }}{{ if .Logins }} ({{ .Logins | englishJoin }}){{ end }}"

  filters:
    exclude:
      - "^build:"
      - "^ci:"
      - "^chore:"
      - "^docs:"
      - "^test:"
      - "^Merge"
      - "^go mod tidy"

  groups:
    - title: "New"
      regexp: "^.*feat(\\([[:word:]-]+\\))?:.*$"
      order: 100

    - title: "Fixed"
      regexp: "^.*fix(\\([[:word:]-]+\\))?:.*$"
      order: 200

    - title: "Refactored"
      regexp: "^.*refactor(\\([[:word:]-]+\\))?:.*$"
      order: 300

    - title: "Documentation"
      regexp: "^.*docs(\\([[:word:]-]+\\))?:.*$"
      order: 400

    - title: "Other changes"
      order: 9999

release:
  draft: true
  footer: |
    ## Full Changelog

    [`{{ .PreviousTag }}...{{ .Tag }}`](https://github.com/dexchat/dex/compare/{{ .PreviousTag }}...{{ .Tag }})
