# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: dex

before:
  hooks:
    - go mod tidy

builds:
  - id: dex
    main: ./cmd/tui
    binary: dex
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  abbrev: 7
  format: "[`{{ .SHA }}`](https://github.com/vaaleyard/dex/commit/{{ .SHA }}): {{ .Message }}{{ if .Logins }} ({{ .Logins | englishJoin }}){{ end }}"

  filters:
    exclude:
      - "^build:"
      - "^ci:"
      - "^chore:"
      - "^docs:"
      - "^test:"
      - "^Merge"
      - "^go mod tidy"

  groups:
    - title: "New"
      regexp: "^.*feat(\\([[:word:]-]+\\))?:.*$"
      order: 100

    - title: "Fixed"
      regexp: "^.*fix(\\([[:word:]-]+\\))?:.*$"
      order: 200

    - title: "Refactored"
      regexp: "^.*refactor(\\([[:word:]-]+\\))?:.*$"
      order: 300

    - title: "Documentation"
      regexp: "^.*docs(\\([[:word:]-]+\\))?:.*$"
      order: 400

    - title: "Other changes"
      order: 9999

release:
  footer: |
    ## Full Changelog

    [`{{ .PreviousTag }}...{{ .Tag }}`](https://github.com/vaaleyard/dex/compare/{{ .PreviousTag }}...{{ .Tag }})
