[servers.libera]
address = "irc.libera.chat"
port = 6667
ssl = false
password = ""
channels = ["#dexchat"]
nickname = "johndex"
username = "jdex"
realname = "John Dex"

[servers.rizon]
address = "irc.rizon.com"
port = 6697
ssl = true
password = ""
channels = ["#engineering"]
nickname = "john.dex"
username = "jdex"
realname = "John Dex"